# Generated by Django 2.2.9 on 2020-02-10 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guru', '0001_initial'),
        ('mapel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mengajar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guru.Guru', verbose_name='Guru')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapel.KkmMapel', verbose_name='Mata Pelajaran')),
            ],
            options={
                'verbose_name_plural': 'Mengajar',
            },
        ),
    ]
