# Generated by Django 2.2.9 on 2020-02-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mengajar', '0002_auto_20200208_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mengajar',
            options={'verbose_name_plural': 'Mengajar'},
        ),
    ]
