# Generated by Django 2.2.9 on 2020-02-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mengajar', '0003_auto_20200208_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mengajar',
            old_name='id_guru',
            new_name='guru',
        ),
        migrations.RenameField(
            model_name='mengajar',
            old_name='id_mapel',
            new_name='mapel',
        ),
    ]
