# Generated by Django 2.2.9 on 2020-02-08 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jurusan', '0002_auto_20200208_0345'),
        ('siswa', '0009_auto_20200208_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jurusan.Kelas')),
                ('id_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.Siswa')),
            ],
        ),
    ]
