# Generated by Django 2.2.9 on 2020-02-10 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tahunajaran', '0001_initial'),
        ('jurusan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mapel', models.CharField(max_length=255, verbose_name='Mata Pelajaran')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Data Mata Pelajaran',
            },
        ),
        migrations.CreateModel(
            name='KkmMapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengetahuan', models.IntegerField(blank=True, null=True)),
                ('ketrampilan', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jurusan.Kelas', verbose_name='Kelas')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapel.Mapel', verbose_name='Mata Pelajaran')),
                ('tahun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tahunajaran.TahunAjaran', verbose_name='Tahun Ajaran')),
            ],
            options={
                'verbose_name_plural': 'KKM Mata Pelajaran',
            },
        ),
        migrations.CreateModel(
            name='DescMapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predikat', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('K', 'K')], max_length=1)),
                ('pengetahuan', models.TextField(blank=True, null=True)),
                ('ketrampilan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapel.KkmMapel')),
            ],
            options={
                'verbose_name_plural': 'Diskripsi Nilai Mata Pelajaran',
            },
        ),
    ]
