# Generated by Django 2.2.9 on 2020-02-08 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jurusan', '0002_auto_20200208_0345'),
        ('tahunajaran', '0003_auto_20200208_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mapel', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Data Mata Pelajaran',
            },
        ),
        migrations.CreateModel(
            name='KkmMapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengetahuan', models.IntegerField(blank=True, null=True)),
                ('ketrampilan', models.IntegerField(blank=True, null=True)),
                ('id_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jurusan.Kelas')),
                ('id_mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapel.DataMapel')),
                ('id_tahun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tahunajaran.TahunAjaran')),
            ],
            options={
                'verbose_name_plural': 'KKM - Mata Pelajaran',
            },
        ),
        migrations.CreateModel(
            name='DescMapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predikat', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('K', 'K')], max_length=1)),
                ('pengetahuan', models.TextField(blank=True, null=True)),
                ('ketrampilan', models.TextField(blank=True, null=True)),
                ('id_mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapel.KkmMapel')),
            ],
            options={
                'verbose_name_plural': 'Diskripsi Nilai Mata Pelajaran',
            },
        ),
    ]
