# Generated by Django 2.2.9 on 2020-02-07 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_mapel', models.CharField(max_length=25)),
                ('nama_mapel', models.CharField(max_length=255)),
                ('pengetahuan', models.IntegerField(max_length=2)),
                ('ketrampilan', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DescMapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predikat', models.CharField(max_length=1)),
                ('pengetahuan', models.CharField(max_length=255)),
                ('keterampilan', models.CharField(max_length=255)),
                ('id_mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapel.Mapel')),
            ],
        ),
    ]
