# Generated by Django 2.2.9 on 2020-02-12 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tahunajaran', '0001_initial'),
        ('mapel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mengajar',
            options={'verbose_name_plural': 'Jadwal Mengajar'},
        ),
        migrations.AddField(
            model_name='mengajar',
            name='tahun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tahunajaran.TahunAjaran', verbose_name='Tahun Ajaran'),
        ),
    ]
