# Generated by Django 2.2.9 on 2020-02-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataMapel',
            new_name='Mapel',
        ),
    ]
