# Generated by Django 2.2.9 on 2020-02-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapel',
            name='ketrampilan',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mapel',
            name='pengetahuan',
            field=models.IntegerField(),
        ),
    ]
