# Generated by Django 2.2.9 on 2020-02-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapel', '0002_auto_20200207_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descmapel',
            old_name='keterampilan',
            new_name='ketrampilan',
        ),
    ]
