# Generated by Django 2.2.9 on 2020-02-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapel', '0002_auto_20200208_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kkmmapel',
            options={'verbose_name_plural': 'KKM Mata Pelajaran'},
        ),
    ]
