# Generated by Django 2.2.9 on 2020-02-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapel', '0003_auto_20200207_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descmapel',
            name='ketrampilan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='descmapel',
            name='pengetahuan',
            field=models.TextField(),
        ),
    ]
