# Generated by Django 2.2.9 on 2020-02-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapel', '0004_auto_20200207_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descmapel',
            name='predikat',
            field=models.CharField(choices=[(1, 'Laki-Laki'), (2, 'Perempuan')], max_length=1),
        ),
    ]
