# Generated by Django 2.2.9 on 2020-02-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapel', '0004_auto_20200208_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapel',
            name='nama_mapel',
            field=models.CharField(max_length=255, verbose_name='Mata Pelajaran'),
        ),
    ]
