# Generated by Django 2.2.9 on 2020-02-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapel', '0005_auto_20200207_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descmapel',
            name='predikat',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('K', 'K')], max_length=1),
        ),
    ]
