# Generated by Django 2.2.9 on 2020-02-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapel', '0005_auto_20200208_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descmapel',
            old_name='id_mapel',
            new_name='mapel',
        ),
        migrations.RenameField(
            model_name='kkmmapel',
            old_name='id_kelas',
            new_name='kelas',
        ),
        migrations.RenameField(
            model_name='kkmmapel',
            old_name='id_mapel',
            new_name='mapel',
        ),
        migrations.RenameField(
            model_name='kkmmapel',
            old_name='id_tahun',
            new_name='tahun',
        ),
    ]
