# Generated by Django 2.2.9 on 2020-02-08 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapel', '0006_auto_20200207_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descmapel',
            options={'verbose_name_plural': 'Diskripsi Nilai Mata Pelajaran'},
        ),
        migrations.AlterModelOptions(
            name='mapel',
            options={'verbose_name_plural': 'Mata Pelajaran'},
        ),
    ]
