# Generated by Django 2.2.9 on 2020-02-10 03:34

from django.db import migrations, models
import django.db.models.deletion
import siswa.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tahunajaran', '0001_initial'),
        ('jurusan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nis', models.CharField(max_length=50, verbose_name='NIS')),
                ('nisn', models.CharField(max_length=50, verbose_name='NISN')),
                ('sex', models.IntegerField(choices=[(1, 'Laki-Laki'), (2, 'Perempuan')], default=1, verbose_name='Jenis Kelamin')),
                ('agama', models.IntegerField(choices=[(1, 'Islam'), (2, 'Katholik'), (3, 'Kristen'), (4, 'Hindu'), (5, 'Budha'), (6, 'Lainnya')], default=1)),
                ('tmp_lahir', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempat Lahir')),
                ('tgl_lahir', models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir')),
                ('foto', models.ImageField(upload_to=siswa.models.unique_file_path)),
                ('nama_ayah', models.CharField(max_length=150)),
                ('nama_ibu', models.CharField(max_length=150)),
                ('pekerjaan_ayah', models.CharField(max_length=150)),
                ('pekerjaan_ibu', models.CharField(max_length=150)),
                ('alamat_ayah', models.TextField()),
                ('telp_ayah', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Siswa',
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jurusan.Kelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.Siswa')),
                ('tahun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tahunajaran.TahunAjaran')),
            ],
            options={
                'verbose_name_plural': 'Data Kelas',
            },
        ),
    ]
