# Generated by Django 2.2.9 on 2020-02-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nis', models.CharField(max_length=50)),
                ('nisn', models.CharField(max_length=50)),
                ('sex', models.IntegerField(choices=[('1', 'Laki-Laki'), ('2', 'Perempuan')])),
                ('agama', models.IntegerField(choices=[('1', 'Islam'), ('2', 'Katholik'), ('3', 'Kristen'), ('4', 'Hindu'), ('5', 'Budha'), ('6', 'Lainnya')])),
                ('foto', models.CharField(max_length=255)),
                ('nama_ayah', models.CharField(max_length=150)),
                ('nama_ibu', models.CharField(max_length=150)),
                ('pekerjaan_ayah', models.CharField(max_length=150)),
                ('pekerjaan_ibu', models.CharField(max_length=150)),
                ('alamat_ayah', models.TextField()),
                ('telp_ayah', models.CharField(max_length=100)),
            ],
        ),
    ]
