# Generated by Django 2.2.9 on 2020-02-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='tgl_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='tmp_lahir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='foto',
            field=models.ImageField(blank=True, upload_to='upload/siswa'),
        ),
    ]
