# Generated by Django 2.2.9 on 2020-02-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0004_auto_20200207_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='foto',
            field=models.CharField(max_length=255),
        ),
    ]
