# Generated by Django 2.2.9 on 2020-02-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0006_auto_20200207_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='foto',
            field=models.ImageField(upload_to='siswa/'),
        ),
    ]
