# Generated by Django 2.2.9 on 2020-02-08 03:45

from django.db import migrations, models
import siswa.models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0007_auto_20200207_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siswa',
            options={'verbose_name_plural': 'Siswa'},
        ),
        migrations.AlterField(
            model_name='siswa',
            name='foto',
            field=models.ImageField(upload_to=siswa.models.unique_file_path),
        ),
    ]
