# Generated by Django 2.2.9 on 2020-02-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0008_auto_20200208_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='nis',
            field=models.CharField(max_length=50, verbose_name='NIS'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nisn',
            field=models.CharField(max_length=50, verbose_name='NISN'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Laki-Laki'), (2, 'Perempuan')], default=1, verbose_name='Jenis Kelamin'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='tgl_lahir',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='tmp_lahir',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempat Lahir'),
        ),
    ]
