# Generated by Django 2.2.9 on 2020-02-08 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jurusan', '0002_auto_20200208_0345'),
        ('siswa', '0009_auto_20200208_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='id_kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jurusan.Kelas'),
        ),
    ]
