# Generated by Django 2.2.9 on 2020-02-08 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jurusan', '0002_auto_20200208_0345'),
        ('tahunajaran', '0003_auto_20200208_0345'),
        ('siswa', '0010_siswa_id_kelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='id_kelas',
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jurusan.Kelas')),
                ('id_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.Siswa')),
                ('id_tahun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tahunajaran.TahunAjaran')),
            ],
        ),
    ]
