# Generated by Django 2.2.9 on 2020-02-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0011_auto_20200208_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kelas',
            options={'verbose_name_plural': 'Data Kelas'},
        ),
    ]
