# Generated by Django 2.2.9 on 2020-02-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0012_auto_20200208_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kelas',
            old_name='id_kelas',
            new_name='kelas',
        ),
        migrations.RenameField(
            model_name='kelas',
            old_name='id_siswa',
            new_name='siswa',
        ),
        migrations.RenameField(
            model_name='kelas',
            old_name='id_tahun',
            new_name='tahun',
        ),
    ]
