# Generated by Django 2.2.9 on 2020-02-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nip', models.CharField(max_length=50)),
                ('sex', models.IntegerField(choices=[('1', 'Laki-Laki'), ('2', 'Perempuan')])),
                ('agama', models.IntegerField(choices=[('1', 'Islam'), ('2', 'Katholik'), ('3', 'Kristen'), ('4', 'Hindu'), ('5', 'Budha'), ('6', 'Lainnya')])),
                ('alamat', models.TextField()),
                ('tmp_lahir', models.CharField(max_length=100)),
                ('tgl_lahir', models.DateField()),
            ],
        ),
    ]
