# Generated by Django 2.2.9 on 2020-02-10 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guru', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guru', to=settings.AUTH_USER_MODEL),
        ),
    ]
