# Generated by Django 2.2.9 on 2020-02-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='agama',
            field=models.IntegerField(choices=[(1, 'Islam'), (2, 'Katholik'), (3, 'Kristen'), (4, 'Hindu'), (5, 'Budha'), (6, 'Lainnya')]),
        ),
        migrations.AlterField(
            model_name='guru',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Laki-Laki'), (2, 'Perempuan')]),
        ),
    ]
