# Generated by Django 2.2.9 on 2020-02-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0002_auto_20200207_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='foto',
            field=models.ImageField(blank=True, default='oko', null=True, upload_to='guru/'),
        ),
    ]
