# Generated by Django 2.2.9 on 2020-02-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0003_guru_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='guru/'),
        ),
    ]
