# Generated by Django 2.2.9 on 2020-02-08 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0004_auto_20200207_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guru',
            options={'verbose_name_plural': 'Guru'},
        ),
    ]
