# Generated by Django 2.2.9 on 2020-02-09 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siswa', '0013_auto_20200209_1059'),
        ('mapel', '0006_auto_20200209_1057'),
        ('jurusan', '0003_auto_20200209_1047'),
        ('tahunajaran', '0003_auto_20200208_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengetahuan', models.CharField(blank=True, max_length=3, null=True)),
                ('keterampilan', models.CharField(blank=True, max_length=3, null=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jurusan.Kelas', verbose_name='Kelas')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapel.KkmMapel', verbose_name='Mata Pelajaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.Siswa')),
                ('tahun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tahunajaran.TahunAjaran', verbose_name='Tahun Ajaran')),
            ],
        ),
    ]
