# Generated by Django 2.2.9 on 2020-02-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raport',
            options={'verbose_name_plural': 'Raport'},
        ),
        migrations.AlterField(
            model_name='raport',
            name='keterampilan',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='raport',
            name='pengetahuan',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
