# Generated by Django 2.2.9 on 2020-02-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raport',
            name='kelas',
        ),
        migrations.RemoveField(
            model_name='raport',
            name='tahun',
        ),
    ]
