# Generated by Django 2.2.9 on 2020-02-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raport', '0002_auto_20200215_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raport',
            options={'verbose_name_plural': 'Nilai Siswa'},
        ),
    ]
