# Generated by Django 2.2.9 on 2020-02-10 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guru', '0001_initial'),
        ('tahunajaran', '0001_initial'),
        ('jurusan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaliKelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guru.Guru')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jurusan.Kelas')),
                ('tahun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tahunajaran.TahunAjaran')),
            ],
            options={
                'verbose_name_plural': 'Wali Kelas',
            },
        ),
    ]
