# Generated by Django 2.2.9 on 2020-02-07 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jurusan', '0001_initial'),
        ('guru', '0002_auto_20200207_0919'),
        ('tahunajaran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaliKelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guru.Guru')),
                ('id_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jurusan.Kelas')),
                ('id_tahun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tahunajaran.TahunAjaran')),
            ],
        ),
    ]
