# Generated by Django 2.2.9 on 2020-02-08 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walikelas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walikelas',
            options={'verbose_name_plural': 'Wali Kelas'},
        ),
    ]
