# Generated by Django 2.2.9 on 2020-02-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walikelas', '0002_auto_20200208_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walikelas',
            old_name='id_guru',
            new_name='guru',
        ),
        migrations.RenameField(
            model_name='walikelas',
            old_name='id_kelas',
            new_name='kelas',
        ),
        migrations.RenameField(
            model_name='walikelas',
            old_name='id_tahun',
            new_name='tahun',
        ),
    ]
