# Generated by Django 2.2.9 on 2020-02-09 12:18

import contentweb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(upload_to=contentweb.models.unique_file_path),
        ),
    ]
