# Generated by Django 2.2.9 on 2020-02-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentweb', '0002_auto_20200209_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='intro',
            field=models.TextField(max_length=755),
        ),
    ]
