# Generated by Django 2.2.9 on 2020-02-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=25)),
                ('status', models.IntegerField(choices=[(1, 'Aktif'), (2, 'Non-Aktif')], max_length=1)),
            ],
        ),
    ]
