# Generated by Django 2.2.9 on 2020-02-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahunajaran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tahunajaran',
            name='status',
            field=models.IntegerField(choices=[(1, 'Aktif'), (2, 'Non-Aktif')]),
        ),
    ]
