# Generated by Django 2.2.9 on 2020-02-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahunajaran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tahunajaran',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Gasal'), (2, 'Genap')], default=1),
        ),
    ]
