# Generated by Django 2.2.9 on 2020-02-08 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tahunajaran', '0002_auto_20200207_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tahunajaran',
            options={'verbose_name_plural': 'Tahun Ajaran'},
        ),
    ]
