# Generated by Django 2.2.9 on 2020-02-08 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurusan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jurusan',
            options={'verbose_name_plural': 'Daftar Jurusan'},
        ),
        migrations.AlterModelOptions(
            name='kelas',
            options={'verbose_name_plural': 'Daftar Kelas'},
        ),
    ]
