# Generated by Django 2.2.9 on 2020-02-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurusan', '0002_auto_20200208_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kelas',
            old_name='id_jurusan',
            new_name='jurusan',
        ),
    ]
